services:
  server:
    build:
      context: ./server
    ports:
      - '8002:5000'
    environment:
      PORT: 5000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: root
      DB_NAME: blog_db
      SECRET_KEY: Javascript is awesome
    depends_on:
    - postgres
    restart: always

  postgres:
    image: postgres:latest
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES USER: postgres
      POSTGRES PASSWORD: root
      POSTGRES_DB: blog_db
    ports:
      - '8003:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: